# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

# Rules by id
MD004: false                  # Unordered list style
MD007:                        # Unordered list indentation
  indent: 2
MD009: false                  # Trailing spaces
MD013:
  line_length: 808            # Line length
MD026:                        # List of not allowed
  punctuation: ".,;:!。，；:"
MD033: false                  # Inline HTML
MD040: false                  # Fenced code blocks should have a language specified
MD041: false                  # First line in file should be a top level heading

# Rules by tags
blank_lines: false  # Error on blank lines
