name: Validate

on: push

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v1
    - id: install-katacoda-cli
      name: Install Katacoda CLI
      run: |
        npm i katacoda-cli --global
    - id: show-environment
      name: Show environment
      run: |
        echo github.repository: ${{ github.repository }}
        echo github.ref: ${{ github.head_ref || github.ref }}
        echo github.sha: ${{ github.sha }}
        katacoda --version

# BUILD AND TEST
    - id: validate
      name: Validate Katacoda scenarios
      run: |
        katacoda validate:all --repo SchemaCrawler-Katacoda-Scenarios
