name: Validate

on: push

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    if: false # Do not build, since the Katacoda command-line is buggy, and does not take steps in a separate folder
    steps:

# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2        
    - id: show-environment
      name: Show environment
      run: |
        echo github.repository: ${{ github.repository }}
        echo github.ref: ${{ github.head_ref || github.ref }}
        echo github.sha: ${{ github.sha }}
        echo github.workspace: ${{ github.workspace }}        

# BUILD AND TEST
    - id: validate-markdown
      name: Validate Katacoda Markdown
      run: |
        sudo gem install mdl
        mdl ${{ github.workspace }}
    - id: validate-katacoda
      name: Validate Katacoda scenarios
      run: |
        sudo npm i katacoda-cli --global
        katacoda --version
        katacoda validate:all --repo ${{ github.workspace }}
